apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-dyv1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-dyv1
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-dyv1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-dyv1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-dyv1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-jury-tenant/nodejs-users/simple-nodejs-app-dyv1@sha256:43498bbedb8776b1460189d76dfd643dde1e71dc928515a790068d1be08258f4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
